version: 2
jobs:
  go:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Go to Go
          command: cd ./Go
      - run:
          name: Install golangci-lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
            golangci-lint --version
      - run:
          name: Lint
          command: golangci-lint --enable-all run

workflows:
  version: 2
  build-test-lint:
    jobs:
      - go
