version: 2
jobs:
  go:
    working_directory: ~/project/Go
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sudo sh -s -- -b $(go env GOPATH)/bin v1.15.0
            golangci-lint --version
      - run:
          name: Lint
          command: golangci-lint run ./redis/... --enable-all

workflows:
  version: 2
  build-test-lint:
    jobs:
      - go
