---
version: "3"

services:
  loki:
    image: grafana/loki:1.6.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:1.6.0
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
    ports:
      - "1514:1514"
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  rsyslog:
    image: rsyslog/syslog_appliance_alpine
    ports:
      - "514:514/udp"
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
