---
name: spell
on:
  push:
    paths:
      - english/
      - .github/workflows/spell.yaml
      - spellcheck.yaml
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rojopolis/spellcheck-github-actions@0.13.0
        name: Spellcheck
